# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Feiko Lai
tagline:          'Hong Kong'
description:      'Software Engineer Focusing on Scalability'
url:              http://dg3feiko.github.io/
baseurl:          /

author:
  name:           'dg3feiko'
  url:            https://twitter.com/dg3f

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           http://dg3feiko.github.io/
