# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Code for Victory
tagline:          'Hong Kong'
description:      'Software Engineering on Both Application and Organization Scalability'
url:              http://dg3feiko.github.io/
baseurl:          /

author:
  name:           'dg3feiko'
  url:            https://twitter.com/dg3f

paginate:         5

# Custom vars
version:          2.1.0
last_updated_at:  Jul 12, 2015

github:
  repo:           https://github.com/dg3feiko
